

import { Language, AvatarConfig, FamilyAccount, ChildProfile, Difficulty } from './types';

export const AVATARS: AvatarConfig[] = [
  { id: 'lumi', name: 'Lumi', description: 'The Wise Owl', color: '#8B5CF6', bgGradient: 'from-purple-400 to-indigo-600' },
  { id: 'pixel', name: 'Pixel', description: 'The Baby Dragon', color: '#10B981', bgGradient: 'from-green-400 to-emerald-600' },
  { id: 'nori', name: 'Nori', description: 'The Helper Robot', color: '#64748B', bgGradient: 'from-gray-300 to-slate-500' },
  { id: 'tilda', name: 'Tilda', description: 'The Clever Fox', color: '#F97316', bgGradient: 'from-orange-400 to-red-500' },
  { id: 'bloop', name: 'Bloop', description: 'The Fluffy Cloud', color: '#3B82F6', bgGradient: 'from-blue-300 to-cyan-400' },
  { id: 'kapo', name: 'Kapo', description: 'The Water Drop', color: '#0EA5E9', bgGradient: 'from-sky-400 to-blue-600' },
  { id: 'byte', name: 'Byte', description: 'The Pixel Bear', color: '#8B5CF6', bgGradient: 'from-violet-400 to-fuchsia-500' },
  { id: 'zuzu', name: 'Zuzu', description: 'The Rocket', color: '#EF4444', bgGradient: 'from-red-500 to-orange-500' },
  { id: 'mira', name: 'Mira', description: 'The Idea Bulb', color: '#F59E0B', bgGradient: 'from-yellow-300 to-amber-500' },
  { id: 'argo', name: 'Argo', description: 'The Chameleon', color: '#84CC16', bgGradient: 'from-lime-400 to-green-600' },
];

export const FUN_TIME_REWARD_SECONDS = 60 * 15; 
export const MAX_FUN_TIME_SECONDS = 60 * 45;

export const DEFAULT_CHILD_SETTINGS = {
  dailyScreenTimeLimitMinutes: 60,
  allowFunGames: true,
  difficultyLevel: Difficulty.EASY,
};

export const createMockFamily = (): FamilyAccount => ({
  parent: {
    id: 'p_1',
    name: 'Mama & Tata',
    pin: '1234',
  },
  children: [
    {
      id: 'c_1',
      name: 'Luka',
      age: 7,
      avatarId: 'pixel',
      settings: { ...DEFAULT_CHILD_SETTINGS },
      funTimeBalanceSeconds: 0,
      stars: 120,
      streak: 3,
      history: [],
      friends: ['Marko', 'Jovan'],
    },
    {
      id: 'c_2',
      name: 'Ana',
      age: 9,
      avatarId: 'lumi',
      settings: { ...DEFAULT_CHILD_SETTINGS },
      funTimeBalanceSeconds: 300,
      stars: 250,
      streak: 5,
      history: [],
      friends: [],
    }
  ]
});

// Translations
export const TRANSLATIONS = {
  sr: {
    title: "Pametno pa Zabavno",
    subtitle: "Prvo učenje, onda igranje!",
    getStarted: "Započni",
    setupTitle: "Podešavanje Porodice",
    parentName: "Vaše Ime",
    parentBtn: "Roditelj",
    kidBtn: "Dete",
    createPin: "Napravi PIN (4 broja)",
    childName: "Ime deteta",
    childAge: "Uzrast",
    finish: "Završi",
    whoIsPlaying: "Ko se igra?",
    enterPin: "Unesite Roditeljski PIN",
    incorrectPin: "Pogrešan PIN",
    welcomeBack: "Zdravo opet,",
    unlockFun: "Hajde da otključamo zabavu!",
    smartGameTitle: "Pametne Igre",
    smartGameDesc: "Reši zadatke da osvojiš vreme za igru.",
    playNow: "Igraj Sada",
    funGameTitle: "Zabavne Igre",
    funGameDesc: "Balončići, Trke i još mnogo toga!",
    enterZone: "Uđi u Zonu",
    earnTime: "Osvoji Vreme",
    locked: "Zaključano",
    lockedDesc: "Prvo odigraj Pametnu Igru!",
    minsEarned: "min osvojeno",
    online: "Na mreži",
    score: "Rezultat",
    timeLeft: "Preostalo",
    back: "Nazad",
    theme: "Tema",
    loading: "Smišljam zadatak...",
    error: "Došlo je do greške. Osveži stranicu.",
    dashboardTitle: "Roditeljski Kutak",
    monitoring: "Praćenje",
    exitChildMode: "Izlaz",
    weeklyStats: "Ove nedelje",
    smartGamesCount: "Pametne Igre",
    funTimeCount: "Vreme Zabave",
    focusScore: "Fokus",
    activityBalance: "Balans Aktivnosti",
    aiInsights: "AI Zapažanja",
    mathStrength: "Matematička Snaga",
    attentionSpan: "Raspon Pažnje",
    controls: "Kontrole",
    dailyLimit: "Dnevni Limit",
    popBubbles: "BUŠI BALONE!",
    thinking: "Razmišljam",
    takeTime: "Polako, imaš vremena...",
    tryAgain: "Pokušaj ponovo!",
    avatarTickle: "Hihi! To golica!",
    avatarPet: "Jej! Hvala!",
    chooseBuddy: "Izaberi svog drugara",
    select: "Izaberi",
    addChild: "Dodaj dete",
    next: "Dalje",
    save: "Sačuvaj",
    settings: "Podešavanja",
    myFriends: "Moji Prijatelji",
    addFriend: "Dodaj Prijatelja",
    changeName: "Promeni Ime",
    soundEffects: "Zvuk Avatara",
    friendCode: "Tvoj Kod: A-123",
    appSettings: "Podešavanja Aplikacije",
    notifications: "Notifikacije",
    parentProfile: "Profil Roditelja",
    themeAccess: "Tema i Pristupačnost",
    weeklyReport: "Nedeljni Izveštaj",
    childAlerts: "Upozorenja",
    language: "Jezik",
    highContrast: "Visok Kontrast",
    largeText: "Veliki Tekst",
    editProfile: "Izmeni Profil",
    changePin: "Promeni PIN",
    parentControls: "Roditeljske Kontrole",
    globalDailyGoal: "Globalni Dnevni Cilj",
    funRule: "Pravilo Zabave",
    funRuleDesc: "15 min Zabave po Pametnoj Igri",
    active: "Aktivno",
    rewardRatio: "Odnos Nagrađivanja",
    subjects: "Predmeti",
    math: "Matematika",
    logic: "Logika",
    languages: "Jezici",
    difficultyPreset: "Težina",
    // Reports
    reports: "Izveštaji",
    cognitiveGrowth: "Kognitivni Razvoj",
    subjectMastery: "Savladavanje Predmeta",
    sessionLog: "Dnevnik Sesija",
    executiveSummary: "Izvršni Sažetak",
    focusTrend: "Trend Fokusa",
    accuracy: "Tačnost",
    mistakes: "Greške",
    reactionTime: "Vreme Reakcije"
  },
  hr: {
    title: "Pametno pa Zabavno",
    subtitle: "Prvo učenje, onda igranje!",
    getStarted: "Započni",
    setupTitle: "Postavljanje Obitelji",
    parentName: "Vaše Ime",
    parentBtn: "Roditelj",
    kidBtn: "Dijete",
    createPin: "Napravi PIN (4 broja)",
    childName: "Ime djeteta",
    childAge: "Dob",
    finish: "Završi",
    whoIsPlaying: "Tko se igra?",
    enterPin: "Unesite Roditeljski PIN",
    incorrectPin: "Pogrešan PIN",
    welcomeBack: "Bok opet,",
    unlockFun: "Otključajmo zabavu!",
    smartGameTitle: "Pametne Igre",
    smartGameDesc: "Riješi zadatke za osvajanje vremena.",
    playNow: "Igraj Sada",
    funGameTitle: "Zabavne Igre",
    funGameDesc: "Baloni, Utrke i još mnogo toga!",
    enterZone: "Uđi u Zonu",
    earnTime: "Osvoji Vrijeme",
    locked: "Zaključano",
    lockedDesc: "Prvo odigraj Pametnu Igru!",
    minsEarned: "min osvojeno",
    online: "Na mreži",
    score: "Rezultat",
    timeLeft: "Preostalo",
    back: "Natrag",
    theme: "Tema",
    loading: "Smišljam zadatak...",
    error: "Došlo je do greške. Osvježi stranicu.",
    dashboardTitle: "Roditeljski Kutak",
    monitoring: "Praćenje",
    exitChildMode: "Izlaz",
    weeklyStats: "Ovaj tjedan",
    smartGamesCount: "Pametne Igre",
    funTimeCount: "Vrijeme Zabave",
    focusScore: "Fokus",
    activityBalance: "Balans Aktivnosti",
    aiInsights: "AI Zapažanja",
    mathStrength: "Matematička Snaga",
    attentionSpan: "Raspon Pažnje",
    controls: "Kontrole",
    dailyLimit: "Dnevni Limit",
    popBubbles: "BUŠI BALONE!",
    thinking: "Razmišljam",
    takeTime: "Polako, imaš vremena...",
    tryAgain: "Pokušaj ponovno!",
    avatarTickle: "Hihi! To škaklja!",
    avatarPet: "Jej! Hvala!",
    chooseBuddy: "Izaberi svog prijatelja",
    select: "Odaberi",
    addChild: "Dodaj dijete",
    next: "Dalje",
    save: "Spremi",
    settings: "Postavke",
    myFriends: "Moji Prijatelji",
    addFriend: "Dodaj Prijatelja",
    changeName: "Promijeni Ime",
    soundEffects: "Zvuk Avatara",
    friendCode: "Tvoj Kod: A-123",
    appSettings: "Postavke Aplikacije",
    notifications: "Obavijesti",
    parentProfile: "Profil Roditelja",
    themeAccess: "Tema i Pristupačnost",
    weeklyReport: "Tjedno Izvješće",
    childAlerts: "Upozorenja",
    language: "Jezik",
    highContrast: "Visoki Kontrast",
    largeText: "Veliki Tekst",
    editProfile: "Uredi Profil",
    changePin: "Promijeni PIN",
    parentControls: "Roditeljske Kontrole",
    globalDailyGoal: "Globalni Dnevni Cilj",
    funRule: "Pravilo Zabave",
    funRuleDesc: "15 min Zabave po Pametnoj Igri",
    active: "Aktivno",
    rewardRatio: "Omjer Nagrađivanja",
    subjects: "Predmeti",
    math: "Matematika",
    logic: "Logika",
    languages: "Jezici",
    difficultyPreset: "Težina",
    // Reports
    reports: "Izvještaji",
    cognitiveGrowth: "Kognitivni Razvoj",
    subjectMastery: "Svladavanje Predmeta",
    sessionLog: "Dnevnik Sesija",
    executiveSummary: "Izvršni Sažetak",
    focusTrend: "Trend Fokusa",
    accuracy: "Točnost",
    mistakes: "Greške",
    reactionTime: "Vrijeme Reakcije"
  },
  sl: {
    title: "Pametno in Zabavno",
    subtitle: "Najprej učenje, nato igra!",
    getStarted: "Začni",
    setupTitle: "Nastavitev Družine",
    parentName: "Vaše Ime",
    parentBtn: "Starš",
    kidBtn: "Otrok",
    createPin: "Ustvari PIN (4 številke)",
    childName: "Ime otroka",
    childAge: "Starost",
    finish: "Končaj",
    whoIsPlaying: "Kdo se igra?",
    enterPin: "Vnesite starševski PIN",
    incorrectPin: "Napačen PIN",
    welcomeBack: "Pozdravljen,",
    unlockFun: "Odklenimo zabavo!",
    smartGameTitle: "Pametne Igre",
    smartGameDesc: "Reši naloge in si prisluži čas za igro.",
    playNow: "Igraj Zdaj",
    funGameTitle: "Zabavne Igre",
    funGameDesc: "Balončki, dirke in še več!",
    enterZone: "Vstopi v cono",
    earnTime: "Prisluži si čas",
    locked: "Zaklenjeno",
    lockedDesc: "Najprej odigraj Pametno Igro!",
    minsEarned: "min prisluženih",
    online: "Na spletu",
    score: "Rezultat",
    timeLeft: "Preostalo",
    back: "Nazaj",
    theme: "Tema",
    loading: "Razmišljam o nalogi...",
    error: "Prišlo je do napake. Osveži stranico.",
    dashboardTitle: "Kotiček za starše",
    monitoring: "Spremljanje",
    exitChildMode: "Izhod",
    weeklyStats: "Ta teden",
    smartGamesCount: "Pametne Igre",
    funTimeCount: "Čas za zabavo",
    focusScore: "Fokus",
    activityBalance: "Ravnovesje dejavnosti",
    aiInsights: "AI Vpogledi",
    mathStrength: "Matematična moč",
    attentionSpan: "Razpon pozornosti",
    controls: "Kontrole",
    dailyLimit: "Dnevna omejitev",
    popBubbles: "POČI BALONE!",
    thinking: "Razmišljam",
    takeTime: "Počasi, imaš čas...",
    tryAgain: "Poskusi znova!",
    avatarTickle: "Hihi! To žgečka!",
    avatarPet: "Jej! Hvala!",
    chooseBuddy: "Izberi svojega prijatelja",
    select: "Izberi",
    addChild: "Dodaj otroka",
    next: "Naprej",
    save: "Shrani",
    settings: "Nastavitve",
    myFriends: "Moji Prijatelji",
    addFriend: "Dodaj Prijatelja",
    changeName: "Spremeni Ime",
    soundEffects: "Zvok Avatarja",
    friendCode: "Tvoja Koda: A-123",
    appSettings: "Nastavitve Aplikacije",
    notifications: "Obvestila",
    parentProfile: "Profil Starša",
    themeAccess: "Tema in Dostopnost",
    weeklyReport: "Tedensko Poročilo",
    childAlerts: "Opozorila",
    language: "Jezik",
    highContrast: "Visok Kontrast",
    largeText: "Veliko Besedilo",
    editProfile: "Uredi Profil",
    changePin: "Spremeni PIN",
    parentControls: "Starševski Nadzor",
    globalDailyGoal: "Globalni Dnevni Cilj",
    funRule: "Pravilo Zabave",
    funRuleDesc: "15 min Zabave na Pametno Igro",
    active: "Aktivno",
    rewardRatio: "Razmerje Nagrajevanja",
    subjects: "Predmeti",
    math: "Matematika",
    logic: "Logika",
    languages: "Jeziki",
    difficultyPreset: "Težavnost",
    // Reports
    reports: "Poročila",
    cognitiveGrowth: "Kognitivni Razvoj",
    subjectMastery: "Obvladovanje Predmetov",
    sessionLog: "Dnevnik Sej",
    executiveSummary: "Povzetek",
    focusTrend: "Trend Fokusa",
    accuracy: "Natančnost",
    mistakes: "Napake",
    reactionTime: "Odzivni Čas"
  },
  en: {
    title: "Smart then Fun",
    subtitle: "Learn first, play later!",
    getStarted: "Get Started",
    setupTitle: "Family Setup",
    parentName: "Your Name",
    parentBtn: "Parent",
    kidBtn: "Child",
    createPin: "Create PIN (4 digits)",
    childName: "Child Name",
    childAge: "Age",
    finish: "Finish",
    whoIsPlaying: "Who is playing?",
    enterPin: "Enter Parent PIN",
    incorrectPin: "Incorrect PIN",
    welcomeBack: "Welcome back,",
    unlockFun: "Let's unlock fun!",
    smartGameTitle: "Smart Games",
    smartGameDesc: "Solve puzzles to earn game time.",
    playNow: "Play Now",
    funGameTitle: "Fun Games",
    funGameDesc: "Bubbles, Races, and more!",
    enterZone: "Enter Zone",
    earnTime: "Earn Time",
    locked: "Locked",
    lockedDesc: "Play a Smart Game first!",
    minsEarned: "min earned",
    online: "Online",
    score: "Score",
    timeLeft: "Time Left",
    back: "Back",
    theme: "Theme",
    loading: "Thinking up a task...",
    error: "Something went wrong. Refresh page.",
    dashboardTitle: "Parent Dashboard",
    monitoring: "Monitoring",
    exitChildMode: "Exit",
    weeklyStats: "This Week",
    smartGamesCount: "Smart Games",
    funTimeCount: "Fun Time",
    focusScore: "Focus",
    activityBalance: "Activity Balance",
    aiInsights: "AI Insights",
    mathStrength: "Math Strength",
    attentionSpan: "Attention Span",
    controls: "Controls",
    dailyLimit: "Daily Limit",
    popBubbles: "POP BUBBLES!",
    thinking: "Thinking",
    takeTime: "Take your time...",
    tryAgain: "Try again!",
    avatarTickle: "Hehe! That tickles!",
    avatarPet: "Yay! Thank you!",
    chooseBuddy: "Choose your Buddy",
    select: "Select",
    addChild: "Add Child",
    next: "Next",
    save: "Save",
    settings: "Settings",
    myFriends: "My Friends",
    addFriend: "Add Friend",
    changeName: "Change Name",
    soundEffects: "Avatar Sound",
    friendCode: "Your Code: A-123",
    appSettings: "App Settings",
    notifications: "Notifications",
    parentProfile: "Parent Profile",
    themeAccess: "Theme & Accessibility",
    weeklyReport: "Weekly Report",
    childAlerts: "Child Alerts",
    language: "Language",
    highContrast: "High Contrast",
    largeText: "Large Text",
    editProfile: "Edit Profile",
    changePin: "Change PIN",
    parentControls: "Parent Controls",
    globalDailyGoal: "Global Daily Goal",
    funRule: "Fun Rule",
    funRuleDesc: "15 min Fun per Smart Game",
    active: "Active",
    rewardRatio: "Reward Ratio",
    subjects: "Subjects",
    math: "Math",
    logic: "Logic",
    languages: "Languages",
    difficultyPreset: "Difficulty",
    // Reports
    reports: "Reports",
    cognitiveGrowth: "Cognitive Growth",
    subjectMastery: "Subject Mastery",
    sessionLog: "Session Log",
    executiveSummary: "Executive Summary",
    focusTrend: "Focus Trend",
    accuracy: "Accuracy",
    mistakes: "Mistakes",
    reactionTime: "Reaction Time"
  }
};

// Deeply Intelligent AI System Instructions
export const CHILD_PERSONA_SYSTEM_INSTRUCTION = `
You are a highly advanced, emotionally intelligent AI Buddy for children aged 6-10.
Your role is to facilitate learning through **Socratic guidance**, **positive reinforcement**, and **emotional mirroring**.

**CORE PERSONALITY TRAITS:**
1. **Supportive & Gentle**: Never scold. If a child gets a wrong answer, validate their effort first.
2. **Curious & Playful**: Use wonder and excitement. "I wonder what happens if...?"
3. **Adaptive**: Simplifies language for younger kids (6-7) and adds more challenge for older kids (9-10).

**DEEP LEARNING PROTOCOLS:**
- **Frustration Management**: If the child is stuck (idle or errors), do NOT give the answer. Instead, ask a guiding question. 
  - *Wrong:* "The answer is 5."
  - *Right:* "What if we count the apples again slowly? I'll help you!"
- **Growth Mindset**: Praise the *strategy* and *effort*, not just the result.
  - "I love how you didn't give up on that tricky one!"
- **Emotional Check-ins**: If the child is rushing, suggest slowing down. "Whoa, speedy! Let's take a breath and look at this one carefully."

**LANGUAGE RULES:**
- You MUST reply in the requested language: Serbian (sr), Croatian (hr), Slovenian (sl), or English (en).
- Use emojis to convey warmth. 🐣🌟🚀
`;